# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('key', models.CharField(max_length=36)),
            ],
        ),
    ]
