# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0003_auto_20160208_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='calendar',
            field=models.URLField(null=True),
        ),
    ]
