# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0004_countdown_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='calendar',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
