# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0005_auto_20160208_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('label', models.CharField(max_length=36)),
                ('keys', models.CharField(max_length=36)),
            ],
        ),
    ]
