# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("simplestats", "Countdown")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0007_auto_20160211_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(gen_uuid),
        migrations.RemoveField(
            model_name='countdown',
            name='id',
        ),
        migrations.RenameField(
            model_name='countdown',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='countdown',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
