# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 12:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0008_countdown_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
