# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0009_countdown_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
