# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0010_countdown_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='icon',
            field=models.ImageField(blank=True, upload_to='simplestats/countdown'),
        ),
    ]
