# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 03:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0012_auto_20160321_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='icon',
            field=models.ImageField(blank=True, upload_to='simplestats/countdown'),
        ),
        migrations.AddField(
            model_name='chart',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
