# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0015_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='unknown', max_length=36),
            preserve_default=False,
        ),
    ]
