# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0016_report_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='owner',
        ),
    ]
