# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0017_remove_report_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
