# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0018_auto_20160508_0608'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together=set([('created', 'key')]),
        ),
    ]
