# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0019_auto_20160508_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='stat',
            name='key',
            field=models.CharField(max_length=64),
        ),
    ]
