# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0020_auto_20160515_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=64)),
                ('tags', models.CharField(max_length=64)),
                ('text', models.TextField()),
            ],
        ),
    ]
