# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0021_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=64)),
            ],
        ),
    ]
