# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0022_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.TextField(),
        ),
    ]
