# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0023_auto_20160718_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='meta',
        ),
        migrations.AddField(
            model_name='chart',
            name='more',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
