# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0025_countdown_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='label',
            field=models.CharField(max_length=64),
        ),
    ]
