# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0026_auto_20160728_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='allday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countdown',
            name='repeating',
            field=models.BooleanField(default=False),
        ),
    ]
