# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0027_auto_20160728_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdown',
            name='meta',
        ),
    ]
