# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0028_auto_20160728_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='countdown',
            name='label',
            field=models.CharField(max_length=64),
        ),
    ]
