# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0031_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('map', models.URLField()),
                ('state', models.CharField(choices=[('', 'Unselected'), ('entered', 'Entered an Area'), ('exited', 'Exited an Area'), ('Do Button', 'Test Entry'), ('Do Note', 'Manual Entry')], max_length=16)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplestats.Location')),
            ],
        ),
    ]
