# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplestats', '0032_movement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('owner', 'name')]),
        ),
    ]
