# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplestats', '0034_delete_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='html',
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('date', 'owner', 'name')]),
        ),
    ]
