# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0035_auto_20170108_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
