# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import simplestats.models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0037_chart_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatMeta',
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='chart',
            name='icon',
            field=models.ImageField(blank=True, upload_to=simplestats.models._upload_to_path),
        ),
        migrations.AlterField(
            model_name='chart',
            name='keys',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='countdown',
            name='icon',
            field=models.ImageField(blank=True, upload_to=simplestats.models._upload_to_path),
        ),
        migrations.AlterField(
            model_name='stat',
            name='key',
            field=models.CharField(max_length=128),
        ),
    ]
