# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0039_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chart',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
