# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 06:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0040_auto_20170902_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
