# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 08:31
from __future__ import unicode_literals

from django.db import migrations


def migrate_objects(apps, schema_editor):
    Widget = apps.get_model("simplestats", "Widget")

    # Countdowns need to migrate the extra values to a simple meta object
    Countdown = apps.get_model("simplestats", "Countdown")
    for c in Countdown.objects.all():
        w = Widget.objects.create(
            slug=c.id,
            title=c.label,
            description=c.description,
            owner_id=c.owner_id,
            icon=c.icon,
            more=c.more,
            public=c.public,
            type='countdown',
        )
        if c.allday:
            w.meta_set.create(key='calendar.allday', value='True')
        if c.repeating:
            w.meta_set.create(key='calendar.repeating', value='True')
        if c.calendar:
            w.meta_set.create(key='calendar.subscription', value=c.calendar)

    # Charts need to migrate to samples and labels
    Chart = apps.get_model("simplestats", "Chart")
    for c in Chart.objects.all():
        w = Widget.objects.create(
            slug=c.id,
            timestamp=c.created,
            owner_id=c.owner_id,
            public=c.public,
            icon=c.icon,
            value=c.value,
            more=c.more,
            title=c.label,
            description=c.keys,
            type='chart',
        )
        for k, v in c.labels.items():
            if k == '__name__' and 'metric' not in c.labels:
                k = 'metric'
            w.label_set.create(name=k, value=v)


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0042_new_widget'),
    ]

    operations = [
        migrations.RunPython(migrate_objects, migrations.RunPython.noop),
    ]
