# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplestats', '0043_widget-migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='countdown',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='data',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='location',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='location',
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='report',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.DeleteModel(
            name='Countdown',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
