# Generated by Django 2.2.2 on 2019-08-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("quickstats", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Scrape",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver",
                    models.CharField(
                        choices=[("icalendar", "Calendar"), ("atom", "Feed")],
                        max_length=32,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickstats.Widget",
                    ),
                ),
            ],
            options={"unique_together": {("widget", "driver")}},
        )
    ]
