# Generated by Django 2.2.2 on 2019-10-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstats', '0002_scrape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
