# Generated by Django 2.2.9 on 2020-05-09 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone



def create_shares(apps, schema_editor):
    Widget = apps.get_model('quickstats', 'Widget')
    Share = apps.get_model('quickstats', 'Share')

    for widget in Widget.objects.filter(public=True):
        Share.objects.create(widget=widget, owner=widget.owner)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstats', '0004_waypoint_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstats.Widget')),
            ],
            options={
                'unique_together': {('owner', 'widget')},
            },
        ),
        migrations.RunPython(create_shares, migrations.RunPython.noop)
    ]
