# Generated by Django 2.2.9 on 2020-07-28 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def fix_owner(apps, schema_editor):
    Scrape = apps.get_model("quickstats", "Scrape")

    for scrape in Scrape.objects.all():
        scrape.owner = scrape.widget.owner
        scrape.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quickstats", "0005_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrape",
            name="owner",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(fix_owner, migrations.RunPython.noop),
    ]
