# Generated by Django 2.2.9 on 2020-12-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstats', '0006_scrape_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='driver',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
