# Generated by Django 2.2.9 on 2020-12-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstats', '0007_longer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='more',
            field=models.URLField(blank=True, max_length=2000, verbose_name='External link'),
        ),
    ]
