# Generated by Django 2.2.18 on 2021-05-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstats', '0008_longer_more_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
