# Generated by Django 2.2.18 on 2021-05-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstats', '0009_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='period',
            field=models.CharField(choices=[('15m', 'Quarter Hour'), ('30m', 'Half Hour'), ('1h', 'Hourly'), ('2h', 'Every other hour'), ('1d', 'Daily')], default='1h', max_length=16),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='driver',
            field=models.CharField(choices=[('atom', 'atom'), ('calendar', 'calendar')], max_length=32),
        ),
    ]
