import simplestats.tasks.countdown
import simplestats.tasks.currency
import simplestats.tasks.feedly
import simplestats.tasks.forecast
import simplestats.tasks.github
import simplestats.tasks.pocket
import simplestats.tasks.reports
import simplestats.tasks.rescuetime
import simplestats.tasks.utility
import simplestats.tasks.wanikani
